- name: Deploy RealWorld Flask App (Conduit)
  hosts: all
  become: true
  vars:
    repo_url: "https://github.com/render-examples/flask-hello-world.git"
    app_dir: "/var/www/conduit"
    # Ці дані ми отримаємо з Terraform outputs
    #db_host: "{{ lookup('env', 'RDS_ENDPOINT') }}" 
    target_region: "{{ AWS_REGION | default('eu-central-1') }}"
    app_s3_bucket: "{{ lookup('amazon.aws.aws_ssm', '/' + target_env + '/s3/app_bucket_name', region=target_region) }}"
    db_host: "{{ lookup('amazon.aws.aws_ssm', '/' + target_env + '/database/endpoint', region=target_region) }}"
    db_password: "{{ lookup('amazon.aws.aws_ssm', '/' + target_env + '/database/password', region=target_region, decrypt=True) }}"

  tasks:
    - name: Debug retrieved values
      debug:
        msg: "Ansible fetched Bucket: {{ app_s3_bucket }} and DB Host: {{ db_host }}, Region: {{ target_region }}"

    - name: Install system dependencies
      yum:
        name: [git, python3, python3-pip, nginx, gcc, python3-devel, postgresql-devel]
        state: present

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        force: yes

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"
        virtualenv_command: "/usr/bin/python3 -m venv"

    - name: Create app config file with DB credentials
      template:
        src: templates/config.py.j2
        dest: /var/www/conduit/config.py

    - name: Configure Gunicorn systemd service
      template:
        src: templates/gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service
      notify: restart gunicorn

    - name: Configure Nginx as Reverse Proxy
      template:
        src: templates/nginx_app.conf.j2
        dest: /etc/nginx/conf.d/conduit.conf
      notify: restart nginx

  handlers:
    - name: restart gunicorn
      systemd: { name: gunicorn, state: restarted, enabled: yes, daemon_reload: yes }
    - name: restart nginx
      systemd: { name: nginx, state: restarted, enabled: yes }