#!/usr/bin/env bash
# =============================================================================
# fetch-runtime-env.sh
#
# Runs as a systemd oneshot service (fastapi-crud-env.service) BEFORE
# fastapi-crud.service starts.
#
# Reads ENV and AWS_DEFAULT_REGION from /etc/fastapi-crud/bootstrap.env
# then fetches all remaining config from SSM and writes
# /etc/fastapi-crud/runtime.env which fastapi-crud.service reads via
# EnvironmentFile=.
#
# Why two files?
#   bootstrap.env — contains only ENV + AWS_DEFAULT_REGION (non-secrets,
#                   safe to write)
#   runtime.env   — contains DATABASE_URL + all secrets; file is 0600,
#                   never committed, regenerated on every boot
# =============================================================================

set -euo pipefail

BOOTSTRAP_ENV="/etc/fastapi-crud/bootstrap.env"
RUNTIME_ENV="/etc/fastapi-crud/runtime.env"
LOG_TAG="fastapi-crud-env"

log() { logger -t "$LOG_TAG" "$*"; echo "[$(date -Is)] $*"; }

# ── 1. Load bootstrap vars ────────────────────────────────────────────────────
if [[ ! -f "$BOOTSTRAP_ENV" ]]; then
  log "ERROR: $BOOTSTRAP_ENV not found — cannot determine ENV/REGION"
  exit 1
fi

# shellcheck source=/dev/null
source "$BOOTSTRAP_ENV"

ENV="${ENV:-dev}"
AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-eu-central-1}"

log "Starting SSM fetch  env=$ENV  region=$AWS_DEFAULT_REGION"

# ── 2. SSM helper ─────────────────────────────────────────────────────────────
ssm_get() {
  local path="$1"
  local decrypt="${2:-false}"
  local args=("ssm" "get-parameter" "--region" "$AWS_DEFAULT_REGION" "--name" "$path")
  [[ "$decrypt" == "true" ]] && args+=("--with-decryption")
  aws "${args[@]}" --query "Parameter.Value" --output text
}

# ── 3. Fetch DB params from SSM ───────────────────────────────────────────────
log "Fetching database params from SSM ..."

DB_HOST=$(ssm_get "/${ENV}/database/endpoint")
DB_PORT=$(ssm_get "/${ENV}/database/port")
DB_NAME=$(ssm_get "/${ENV}/database/name")
DB_USER=$(ssm_get "/${ENV}/database/username")
DB_PASS=$(ssm_get "/${ENV}/database/password" "true")

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

log "Database host: ${DB_HOST}:${DB_PORT}/${DB_NAME} (password redacted)"

# ── 4. Write runtime.env (readable only by root / app service) ───────────────
install -d -m 0700 "$(dirname "$RUNTIME_ENV")"

cat > "$RUNTIME_ENV" <<EOF
# Auto-generated by fetch-runtime-env.sh on $(date -Is)
# DO NOT EDIT — regenerated on every boot

ENV=${ENV}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

# Database
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASS}
DATABASE_URL=${DATABASE_URL}
EOF

chmod 0600 "$RUNTIME_ENV"

log "runtime.env written successfully — fastapi-crud.service may now start"