name: Build Golden Image (Packer)

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for build image'
        required: false
        default: 'Manual rebuild'
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options: [dev, stage, prod]
  # push:
  #   branches: [ "main" ]
  #   paths:
  #     - 'ansible/**'    
  #     - 'packer/**'     

env:
  AWS_REGION: "eu-central-1"
  PROJECT_ENV: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  packer-build:
    name: 'Packer Build AMI'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Packer Init
        working-directory: ./packer
        run: packer init .

      - name: Packer Validate
        working-directory: ./packer
        run: packer validate .
        env:
          PROJECT_ENV: ${{ env.PROJECT_ENV }}

      - name: Packer Build
        working-directory: ./packer
        run: packer build .
        env:
          PROJECT_ENV: ${{ env.PROJECT_ENV }}
          AWS_REGION:  ${{ env.AWS_REGION }}

      - name: Summary
        run: |
          echo "### ✅ Golden Image Built" >> "$GITHUB_STEP_SUMMARY"
          echo "| Key | Value |" >> "$GITHUB_STEP_SUMMARY"
          echo "|-----|-------|" >> "$GITHUB_STEP_SUMMARY"
          echo "| AMI ID | \`${{ steps.ami.outputs.ami_id }}\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Region | \`${{ env.AWS_REGION }}\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| Environment | \`${{ env.PROJECT_ENV }}\` |" >> "$GITHUB_STEP_SUMMARY"
          echo "| SSM key | \`/${{ env.PROJECT_ENV }}/app/ami_id\` |" >> "$GITHUB_STEP_SUMMARY"
