name: Application Deployment (Ansible)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ansible/**' # Запуск тільки при зміні папки з Ansible

env:
  AWS_REGION: "eu-central-1"
  PROJECT_ENV: "dev"

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Ansible and AWS dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Run Ansible Playbook
        run: |
          cd ansible
          ansible-playbook playbook.yml \
            -e "target_env=${{ env.PROJECT_ENV }}" \
            -e "aws_region=${{ env.AWS_REGION }}"
