name: Infrastructure Creation (Terragrunt)

on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose the environment for deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - stage
          - prod

  # Run on merge/push to main
  push:
    branches: [ "main" ]
    paths:
      - 'terraform/**'
      
  # Run check when creating a Pull Request
  pull_request:
    branches: [ "main" ]
    paths:
      - 'terraform/**'

# Global variables
env:
  AWS_REGION: "eu-central-1"
  TG_ENV: ${{ github.event.inputs.target_env || 'dev' }}
  TG_STATE_BUCKET: "tfstate-buckets3-2026"


permissions:
  id-token: write   
  contents: read

jobs:
  terragrunt:
    name: 'Terragrunt Checks & Apply'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.5" 
          terraform_wrapper: false   

      # Install Terragrunt
      - name: Setup Terragrunt
        run: |
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.11/terragrunt_linux_amd64
          mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
          terragrunt --version

      - name: Format Check (HCL)
        working-directory: ./terraform
        run: terragrunt hclfmt --terragrunt-check

      - name: Terragrunt Init
        working-directory: ./terraform/environments/${{ env.TG_ENV }}
        run: terragrunt run-all init --terragrunt-non-interactive

      - name: Validate Code
        working-directory: ./terraform/environments/${{ env.TG_ENV }}
        run: terragrunt run-all validate --terragrunt-non-interactive

      - name: Terragrunt Plan
        id: plan
        working-directory: ./terraform/environments/${{ env.TG_ENV }}
        run: terragrunt run-all plan --terragrunt-non-interactive

      # Runs only if it is a push to main OR a manual run 
      - name: Terragrunt Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        working-directory: ./terraform/environments/${{ env.TG_ENV }}
        run: terragrunt run-all apply --terragrunt-non-interactive
        
      - name: Install Graphviz (for dot command)
        run: sudo apt-get update && sudo apt-get install -y graphviz

# (Твій попередній крок генерації графа)
      - name: Generate Infrastructure Graph
        run: terragrunt graph-dependencies | dot -Tsvg > architecture_modules.svg
        working-directory: ./terraform/environments/${{ env.TG_ENV }}

      # Збереження артефакту
      - name: Upload Architecture Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws-infrastructure-graph
          path: ./terraform/environments/${{ env.TG_ENV }}/architecture_modules.svg
          retention-days: 2 # Оптимізуємо місце, зберігаємо 2 тижні
